// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: api/proto/url/v1/url.proto

package urlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserId        *int64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	ExpiresIn     *int64                 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3,oneof" json:"expires_in,omitempty"` // seconds
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRequest) Reset() {
	*x = CreateURLRequest{}
	mi := &file_api_proto_url_v1_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRequest) ProtoMessage() {}

func (x *CreateURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_url_v1_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRequest.ProtoReflect.Descriptor instead.
func (*CreateURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_url_v1_url_proto_rawDescGZIP(), []int{0}
}

func (x *CreateURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateURLRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *CreateURLRequest) GetExpiresIn() int64 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *CreateURLRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_api_proto_url_v1_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_url_v1_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_url_v1_url_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type URLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *int64                 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	ClickCount    int64                  `protobuf:"varint,6,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLResponse) Reset() {
	*x = URLResponse{}
	mi := &file_api_proto_url_v1_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLResponse) ProtoMessage() {}

func (x *URLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_url_v1_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLResponse.ProtoReflect.Descriptor instead.
func (*URLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_url_v1_url_proto_rawDescGZIP(), []int{2}
}

func (x *URLResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *URLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *URLResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *URLResponse) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *URLResponse) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

type ValidateURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateURLRequest) Reset() {
	*x = ValidateURLRequest{}
	mi := &file_api_proto_url_v1_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateURLRequest) ProtoMessage() {}

func (x *ValidateURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_url_v1_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateURLRequest.ProtoReflect.Descriptor instead.
func (*ValidateURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_url_v1_url_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	IsSafe        bool                   `protobuf:"varint,2,opt,name=is_safe,json=isSafe,proto3" json:"is_safe,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	mi := &file_api_proto_url_v1_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_url_v1_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_url_v1_url_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidationResponse) GetIsSafe() bool {
	if x != nil {
		return x.IsSafe
	}
	return false
}

func (x *ValidationResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_api_proto_url_v1_url_proto protoreflect.FileDescriptor

const file_api_proto_url_v1_url_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/url/v1/url.proto\x12\x06url.v1\"\x82\x02\n" +
	"\x10CreateURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03H\x01R\texpiresIn\x88\x01\x01\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.url.v1.CreateURLRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_expires_in\".\n" +
	"\rGetURLRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"\xdf\x01\n" +
	"\vURLResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\"\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03H\x00R\texpiresAt\x88\x01\x01\x12\x1f\n" +
	"\vclick_count\x18\x06 \x01(\x03R\n" +
	"clickCountB\r\n" +
	"\v_expires_at\"&\n" +
	"\x12ValidateURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"p\n" +
	"\x12ValidationResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x17\n" +
	"\ais_safe\x18\x02 \x01(\bR\x06isSafe\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason2\xc5\x01\n" +
	"\n" +
	"URLService\x12:\n" +
	"\tCreateURL\x12\x18.url.v1.CreateURLRequest\x1a\x13.url.v1.URLResponse\x124\n" +
	"\x06GetURL\x12\x15.url.v1.GetURLRequest\x1a\x13.url.v1.URLResponse\x12E\n" +
	"\vValidateURL\x12\x1a.url.v1.ValidateURLRequest\x1a\x1a.url.v1.ValidationResponseB&Z$url-shortener/api/proto/url/v1;urlpbb\x06proto3"

var (
	file_api_proto_url_v1_url_proto_rawDescOnce sync.Once
	file_api_proto_url_v1_url_proto_rawDescData []byte
)

func file_api_proto_url_v1_url_proto_rawDescGZIP() []byte {
	file_api_proto_url_v1_url_proto_rawDescOnce.Do(func() {
		file_api_proto_url_v1_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_url_v1_url_proto_rawDesc), len(file_api_proto_url_v1_url_proto_rawDesc)))
	})
	return file_api_proto_url_v1_url_proto_rawDescData
}

var file_api_proto_url_v1_url_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_url_v1_url_proto_goTypes = []any{
	(*CreateURLRequest)(nil),   // 0: url.v1.CreateURLRequest
	(*GetURLRequest)(nil),      // 1: url.v1.GetURLRequest
	(*URLResponse)(nil),        // 2: url.v1.URLResponse
	(*ValidateURLRequest)(nil), // 3: url.v1.ValidateURLRequest
	(*ValidationResponse)(nil), // 4: url.v1.ValidationResponse
	nil,                        // 5: url.v1.CreateURLRequest.MetadataEntry
}
var file_api_proto_url_v1_url_proto_depIdxs = []int32{
	5, // 0: url.v1.CreateURLRequest.metadata:type_name -> url.v1.CreateURLRequest.MetadataEntry
	0, // 1: url.v1.URLService.CreateURL:input_type -> url.v1.CreateURLRequest
	1, // 2: url.v1.URLService.GetURL:input_type -> url.v1.GetURLRequest
	3, // 3: url.v1.URLService.ValidateURL:input_type -> url.v1.ValidateURLRequest
	2, // 4: url.v1.URLService.CreateURL:output_type -> url.v1.URLResponse
	2, // 5: url.v1.URLService.GetURL:output_type -> url.v1.URLResponse
	4, // 6: url.v1.URLService.ValidateURL:output_type -> url.v1.ValidationResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_url_v1_url_proto_init() }
func file_api_proto_url_v1_url_proto_init() {
	if File_api_proto_url_v1_url_proto != nil {
		return
	}
	file_api_proto_url_v1_url_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_url_v1_url_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_url_v1_url_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_url_v1_url_proto_rawDesc), len(file_api_proto_url_v1_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_url_v1_url_proto_goTypes,
		DependencyIndexes: file_api_proto_url_v1_url_proto_depIdxs,
		MessageInfos:      file_api_proto_url_v1_url_proto_msgTypes,
	}.Build()
	File_api_proto_url_v1_url_proto = out.File
	file_api_proto_url_v1_url_proto_goTypes = nil
	file_api_proto_url_v1_url_proto_depIdxs = nil
}
